site_name: Integrify-Backend
site_url: https://github.com/Integrify-Finland/integrify-system-backend/tree/test
site_description: Project documentation with Markdown.
site_author: Integrify-Backend Team

repo_url: https://github.com/Integrify-Finland/integrify-system-backend/tree/test
edit_uri: ""

nav:
    - Home: README.md

copyright: Copyright &copy; 2018  Integrify-Backend Team.
 
plugins:
    - search